# Generated by Django 4.1.1 on 2022-11-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombresocio', models.CharField(max_length=50)),
                ('fechaincorporacion', models.IntegerField()),
                ('añodenacimiento', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('correoelectronico', models.EmailField(max_length=254)),
                ('estado', models.CharField(choices=[('VIGENTE', 'VIGENTE'), ('SUSPENDIDO', 'SUSPENDIDO'), ('RETIRADO', 'RETIRADO')], max_length=20)),
                ('sexo', models.CharField(max_length=200)),
            ],
        ),
    ]
